### ISSUE TITLE
Fix metabox responsive styling

### ISSUE THREAD

**Issue by IreneStr** [Yoast/gutenberg#31] opened 2018-03-01 10:06 UTC
Fixes include, may not be limited to, the things indicated in the following image. Use the meta box of the classic editor as a guideline.
<img width="633" alt="schermafbeelding_2018-03-01_om_11_00_59" src="https://user-images.githubusercontent.com/17744553/36838817-80f8ffee-1d40-11e8-8916-0fa480d1bada.png">

**Comment by hydeenoble** [comment] 2018-03-01 10:19
Hi @IreneStr,

I would like to take this up,  But can you be more descriptive about the exact thing to be done?

thnaks.

**Comment by IreneStr** [comment] 2018-03-01 10:52
Hi @hydeenoble, It's great to hear you'd like to contribute 🙂 

The gist of this issue is to make the responsive view of the metabox in Gutenberg look exactly the same as the responsive view of the metabox in the classic editor. 

So it should look like this:

<img width="693" alt="schermafbeelding 2018-03-01 om 11 27 00" src="https://user-images.githubusercontent.com/17744553/36839862-7f21ee6c-1d43-11e8-8fb3-6ca0dd3a7dd7.png">

The things I saw at a quick glance were:
- The underlining of the traffic light.
- The `need help?` button and `Go Premium` link should be aligned.
- The star before `Go Premium` overlaps the text.

But like I said, you might discover more issues in the process.

During fixing, please continuously compare the metabox in the classic editor and the one in Gutenberg to make sure you don't introduce new differences. 

NB. Colors, the small bullets on the tabs, etc. do not belong to the scope of this issue. There are separate issues for that: #24 #25 #27 #28 #29 #30

**Comment by IreneStr** [comment] 2018-03-01 10:56
@hydeenoble Addition: Please keep in mind our contributing guidelines: https://github.com/Yoast/wordpress-seo/blob/trunk/.github/CONTRIBUTING.md#i-want-to-create-a-patch

**Comment by afercia** [comment] 2018-03-02 13:07
As far as I see, there are at least 2 Gutenberg CSS rules that are the root cause of these issuesL

Gutenberg switches everything to `box-sizing: border-box`, a already mentioned in https://github.com/Yoast/gutenberg/issues/28

```
.gutenberg * {
    box-sizing: border-box;
}
```

Also, it modifies the styling applied to the meta boxes `inside` area:
```
.edit-post-meta-boxes-area .postbox>.inside {
    border-bottom: 1px solid #e2e4e7;
    color: #555d66;
    padding: 15px;
    margin: 0;
}
```

in this case it's the `padding: 15px;` vs. the default WordPress `padding: 0 12px 12px;`

**Comment by afercia** [comment] 2018-03-02 13:59
See related Gutenberg issue: https://github.com/WordPress/gutenberg/issues/5353

**Comment by afercia** [comment] 2018-03-02 16:20
See Gutenberg PR for the `.inside` top padding: https://github.com/WordPress/gutenberg/pull/5357

**Comment by IreneStr** [comment] 2018-03-07 09:05
@hydeenoble, can you please give me an update? Are you currently working on this?

**Comment by afercia** [comment] 2018-03-07 09:45
The Gutenberg PR for the top padding has been merged: https://github.com/WordPress/gutenberg/pull/5357

This should solve the alignment of "Need Help" and "Go Premium" in the top part of the meta box.

**Comment by afercia** [comment] 2018-03-12 13:10
Gutenberg PR for the box-sizing issue: https://github.com/WordPress/gutenberg/pull/5433

**Closed** 2018-03-16 09:49 UTC
Labels: gutenberg-review ★
